name: neurobagel_manage

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    environment:
      - DEFAULT_EMAIL=info@neurobagel.org
    volumes_from:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy

  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    command: --admin-password-file /tmp/portainer_password
    ports:
      - 9443:9443
    volumes:
      - portainer_data:/data
      - ./secrets/portainer_password:/tmp/portainer_password
      - /var/run/docker.sock:/var/run/docker.sock

  tunnel:
    container_name: cloudflared-tunnel
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      TUNNEL_TOKEN: ${CLOUDFLARE_TOKEN}

volumes:
  conf:
  vhost:
  html:
  certs:
  acme:
  portainer_data:

networks:
  proxy: